name: Python Security Scan, SBOM Generation, and PR Handling

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  bandit-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit security scan
        run: bandit -r . -lll || true

      - name: Comment based on Bandit scan result
        uses: actions/github-script@v5
        with:
          script: |
            const issueNumber = github.context.payload.issue?.number;
            const prNumber = github.context.payload.pull_request?.number;
            const repoOwner = github.context.repo.owner;
            const repoName = github.context.repo.repo;

            const commentBody = `High severity issues found. Please review the Bandit scan results.`;

            // Function to post a comment
            async function postComment(issueOrPrNumber) {
              await github.rest.issues.createComment({
                owner: repoOwner,
                repo: repoName,
                issue_number: issueOrPrNumber,
                body: commentBody
              });
            }

            if (issueNumber) {
              await postComment(issueNumber);
            } else if (prNumber) {
              await postComment(prNumber);
            } else {
              console.log('No issue or pull request context found.');
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sbom-generation:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: bandit-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM with Syft
        run: syft packages dir:. -o cyclonedx-json=sbom.json

      - name: Upload SBOM as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: SBOM
          path: sbom.json
