name: Python Security Scan, SBOM Generation, and PR Handling

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  bandit-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit security scan
        run: bandit -r . -lll || true

      - name: Comment on PR based on Bandit result
        uses: actions/github-script@v5
        with:
          script: |
            const contextPayload = github.context.payload;
            const issueOrPrNumber = contextPayload.issue?.number || contextPayload.pull_request?.number;
            const owner = github.context.repo.owner;
            const repo = github.context.repo.repo;
            const message = "High severity issues found. Please review the Bandit scan results.";
            
            if (issueOrPrNumber) {
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: issueOrPrNumber,
                body: message
              });
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sbom-generation:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: bandit-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM with Syft
        run: syft packages dir:. -o cyclonedx-json=sbom.json

      - name: Upload SBOM as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: SBOM
          path: sbom.json
