name: Python Security Scan and PR Handling

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  bandit-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit security scan
        id: bandit_scan
        run: |
          bandit -r . -lll -o results.txt || true
          if grep -q 'Severity: HIGH' results.txt; then
           echo "ISSUE_FOUND=true" >> $GITHUB_ENV
          else
           echo "ISSUE_FOUND=false" >> $GITHUB_ENV

      - name: Print Bandit results
        run: cat results.txt

      - name: Comment 'Block' if critical issues are found
        if: env.ISSUE_FOUND == 'true'
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: 'Block - High vulnerability identified.'
            })
            core.setFailed('Critical vulnerabilities found.')

      - name: Comment 'Successful' if no critical issues
        if: env.ISSUE_FOUND == 'false'
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: 'Successful - No critical vulnerabilities found. This PR will be auto-merged shortly.'
            })

      - name: Auto-Merge Pull Request
        if: env.ISSUE_FOUND == 'false'
        uses: repo-sync/github-sync@v2
        with:
          source_repo: ${{ github.repository }}
          destination_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ${{ github.head_ref }}

  sbom-and-dependency-reporting:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: bandit-security-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate SBOM
        run: echo "SBOM generation step"

      - name: Dependency Scanning
        run: echo "Dependency scanning step"

      - name: Upload SBOM as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: SBOM
          path: path/to/your-sbom-file
